I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 95, in script
    if random(1,5) == 5:
  File "game/script.rpy", line 95, in <module>
    if random(1,5) == 5:
NameError: name 'random' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 95, in script
    if random(1,5) == 5:
  File "C:\Users\Jurya\Documents\RenPy\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Jurya\Documents\RenPy\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Jurya\Documents\RenPy\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 95, in <module>
    if random(1,5) == 5:
NameError: name 'random' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Skeletonknight 1.0
Fri Mar 24 08:18:04 2023
